### ISSUE TITLE
Downloading US file 404's

### ISSUE THREAD

**Issue by scottwoodall** [symerio/pgeocode#16]
The US file no longer exists http://download.geonames.org/export/zip/US.zip and the code throws a 404 when trying to download it.

```
HTTPError
HTTP Error 404: Not Found
```

**Comment by scottwoodall** [comment]
This file now exists again.

 ¯\_(ツ)_/¯

**Comment by rth** [comment]
Thanks for the report!

We changed the download URL in https://github.com/symerio/pgeocode/pull/15 recently but it looks like the old one works again..

**Comment by scottwoodall** [comment]
Sorry about the dupe bug report. I searched before posting but I guess that was a pre-coffee moment.

Thanks for maintaining this library!
