### ISSUE TITLE
Cannot create nominatim for country codes AS, LT, VA

### ISSUE THREAD

**Issue by bcipolli** [symerio/pgeocode#17]
I have a set of zip codes that I need to decode to countries. To do so, I plan to query each nominatim and return any country where a match is found.

In trying to instantiate each nominatum, I received an error: 

```
import pgeocode
nomis = {cc: pgeocode.Nominatim(cc) for cc in pgeocode.COUNTRIES_VALID}
```

When investigating: 
```
for cc in pgeocode.COUNTRIES_VALID:
     try:
         pgeocode.Nominatim(cc)
     except Exception as ex:
         print(cc, ex)
```

I get: 
```
AS No numeric types to aggregate
LT sequence item 1: expected str instance, float found
VA No numeric types to aggregate
```

Suggest either investigating, or dropping from the valid countries list. Thanks!

**Comment by rth** [comment]
Thanks @bcipolli ! Sound like a bug. Do you want to investigate ? :) A full traceback would also be helpful.

Initially I wasn't keen on running unit tests for all countries, as that would mean downloading all datasets for each CI run, but given that the datasets also get updated with time, maybe there is no way around it.

**Comment by bcipolli** [comment]
@rth Three different issues; would you prefer 3 tickets?

* `AS` - missing column headers in the raw downloaded file
* `LT` - one place name is blank, converted to `np.nan`, which fails in a later `groupby`
* `VA` - only column headers (no data) in the raw downloaded file, fails a `groupby`

Lemme know how you'd like to solve, I can likely push up a PR for code changes.

**Comment by rth** [comment]
Sorry for late reply. Essentially we need to add logic [here](https://github.com/symerio/pgeocode/blob/8e63cb35d300605e6789625aac57b0663f7c1108/pgeocode.py#L81) (possibly as a separate function) to fix incorrect data for these countries. If you are still interested don't hesitate to make a PR.
