### ISSUE TITLE
pandas 1.0.1 _infer_compression error

### ISSUE THREAD

**Issue by christopherpryer** [symerio/pgeocode#28]
requirements.txt
```
numpy==1.18.1
pandas==1.0.1
pgeocode==0.1.2
```

test.py
```
import pgeocode
nomi = pgeocode.Nominatim('fr')
```

error:
```
>\venv\lib\site-packages\pgeocode.py (line 69, in _get_data)
>from pandas.io.common import get_filepath_or_buffer, _infer_compression
```

**Comment by rth** [comment]
Could you please post the full traceback?

**Comment by christopherpryer** [comment]
upgraded to 0.2.1

**Comment by rth** [comment]
> upgraded to 0.2.1

If it failed with 0.2.0 it's likely it will fail with 0.2.1 as well.

**Comment by christopherpryer** [comment]
> Could you please post the full error traceback?

Another error started this. I was getting ```AttributeError: Can only use .str accessor with string values!```. After updating pgeocode #28 resolved but I'll probably start a new issue for the AttributeError if I cant figure it out in a bit.
