### ISSUE TITLE
Query location not working at all.

### ISSUE THREAD

**Issue by DanielIAvila** [symerio/pgeocode#29]
Hi,

The function `query_location` is not working at all. I found this [website](http://pydoc.net/pgeocode/0.1.0/pgeocode/) with the background information for pgeocode 0.1.0 and it seems the function has as argument `pass`.

My pgeocode version is 0.2.1.

**Comment by rth** [comment]
Yes, indeed, it looks like it's currently not implemented. Pull request would welcome it improve it!

**Comment by DanielIAvila** [comment]
Roman, like myself, implementing it via GitHub? Let me see how to do that.
