### ISSUE TITLE
Pgeocode | HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by nikzjadhav** [symerio/pgeocode#44]
Hello ,

I am using pgeocode to fetch longitude and latitude from postal code. 
as i am using this package from last few months i am facing issue of HTTP 

![image](https://user-images.githubusercontent.com/41261202/92929560-5d70d400-f45e-11ea-9b8d-d0eee87af73b.png)

currently this issue happening more frequently than past.
This is hampering my pipeline run as well. 

can you please give me solution or way around for this problem.

Thanks and regards,
nikhil

**Comment by diegopescoalcalde** [comment]
I'm also having that.

**Comment by P-S-1987** [comment]
Hi,

I have the same issue. Did you guys figure out what to do?

Thanks

**Comment by Laxminarayen** [comment]
I am facing the same issue as well! Any fixes??

**Comment by rth** [comment]
Thanks for the report. Yes, it's a known issue and we need to host data files in a more reliable location. This was recently done by mirroring those files in https://github.com/symerio/postal-codes-data and serving them via https://symerio.github.io/postal-codes-data/ . 

Next step would be to make changes in the code to fallback to this location when the original one is not working. Additional complexity is that in this second location files are directly served in in the .txt file without being included in a .zip so the load function would be slightly different.

Overall I'll try to look into this in the near future.
