### ISSUE TITLE
Include a requirements.txt

### ISSUE THREAD

**Issue by ryanbwolf** [symerio/pgeocode#52]
Super easy fix, will save tons of dependency headaches.

`pip freeze > requirements.txt`

**Comment by rth** [comment]
The list of dependencies are in [setup.py](https://github.com/symerio/pgeocode/blob/223f7202949c2c6c928fb33143b177acc415a7ce/setup.py#L51), so I'm not sure what would be the advantage of adding a `requirements.txt`

**Comment by rth** [comment]
Closing but don't hesitate to comment if you disagree.
