### ISSUE TITLE
Find cities at a specific distance

### ISSUE THREAD

**Issue by datapolitical** [symerio/pgeocode#57]
Given a location and a distance, what's the right way to find populated places that are exactly that distance from the location?

I don't want to search for everything inside a circle, just what is on its perimeter.

Thanks!

**Comment by rth** [comment]
You could query cities within radius R, those within radius R-epsilon and do the difference between the two sets. Not that with float comparison exact equality doesn't really make sense, so you would need to pick some reasonable value for eplison, of a a few km at least probably.

Don't hestiate to comment futher, if this doesn't work.
