### ISSUE TITLE
country code DZ is not responding

### ISSUE THREAD

**Issue by dalwindr** [symerio/pgeocode#61]
import pgeocode
nomi = pgeocode.Nominatim()

if "DZ" in pgeocode.COUNTRIES_VALID:
    print("country found")
    nomi = pgeocode.Nominatim("DZ")
    zipcodes = ["30200"]
    for i in nomi.query_postal_code(zipcodes).to_dict("records"):
        print("-----", i)

<img width="586" alt="image" src="https://user-images.githubusercontent.com/48798210/173320817-e2f03cf2-892c-46e6-82c4-094bd6ec8c83.png">

**Comment by rth** [comment]
It was likely a temporary issue with the server hosting the data. Should be fixed now.
