### ISSUE TITLE
Shows less distance between two postal codes

### ISSUE THREAD

**Issue by ak4zh** [symerio/pgeocode#84]
I have tried with multiple postal codes and the distance calculated is 25%-30% lesser than what google maps suggest.
Is there a way to get more accurate distance?

```python
import pgeocode

dist = pgeocode.GeoDistance('in')
dist.query_postal_code("629702", "180001")
```
Returns: 2752 kms
As per google maps it's 3400 kms

**Comment by rth** [comment]
This is expected,
 - pgeocode gives you distance between two coordinates if you go in a straight line
 - google maps gives you the distance of the fastest road if you travel by car (or other means of transportation). It's often faster to use larger roads even if if it means traveling in this case 600km more.
 
 The correct distance is in this case given by pgeocode. Closing but don't hesitate to comment.
